version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  mongo_humano:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo_satelite:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  registro:
    image: alertas/node
    build: ./registro
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - ./registro:/usr/app
    depends_on:
      - kafka
      - mongo_humano
      - mongo_satelite

  consulta:
    image: alertas/node
    build: ./consulta
    command: npm start
    ports:
      - '3001:3000'
    volumes:
      - ./consulta:/usr/app
    depends_on:
      - kafka
      - mongo_humano
      - mongo_satelite

  emissao:
    image: alertas/node
    build: ./emissao
    command: npm start
    volumes:
      - ./emissao:/usr/app
    depends_on:
      - kafka
      - registro
