version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    image: 'wurstmeister/zookeeper:latest'
    ports:
      - '2181:2181'

  kafka:
    container_name: kafka
    image: 'wurstmeister/kafka:2.11-1.1.0'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    depends_on:
      - zookeeper

  banco-mongo-humano:
    container_name: bancoDeDadosDeAlertasdeHumano
    image: mongo
    ports:
      - '27019:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  banco-mongo-satelite:
    container_name: bancoDeDadosDeAlertasDeSatelite
    image: mongo
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  registro:
    container_name: registro
    build: ./registro
    command: sh -c "npm install && npm start"
    ports:
      - '3000:3000'
    volumes:
      - './registro:/usr/app'
    depends_on:
      - kafka
      - banco-mongo-humano
      - banco-mongo-satelite

  consulta-humano:
    container_name: consultaHumano
    build: ./consulta-humano
    command: sh -c "npm install && npm start"
    ports:
      - '3001:3000'
    volumes:
      - './consulta-humano:/usr/app'
    depends_on:
      - banco-mongo-humano

  consulta-satelite:
    container_name: consultaSatelite
    build: ./consulta-satelite
    command: sh -c "npm install && npm start"
    ports:
      - '3002:3000'
    volumes:
      - './consulta-satelite:/usr/app'
    depends_on:
      - banco-mongo-satelite

  emissao-humano:
    container_name: emissaoHumano
    build: ./emissao-humano
    command: sh -c "npm install && npm start"
    volumes:
      - './emissao-humano:/usr/app'
    depends_on:
      - registro
      - kafka

  emissao-satelite:
    container_name: emissaoSatelite
    build: ./emissao-satelite
    command: sh -c "npm install && npm start"
    volumes:
      - './emissao-satelite:/usr/app'
    depends_on:
      - registro
      - kafka

  simulacao-satelite:
    container_name: simulacaoSatelite
    build: ./simulacao-satelite
    command: sh -c "npm install && npm start"
    ports:
      - '3003:3000'
    volumes:
      - './simulacao-satelite:/usr/app'
    depends_on:
      - registro

