version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - ":2181:2181"
    hostname: "zookeeper"
    networks: 
        - local

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    hostname: "kafka"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks: 
      - local

  mongo_humano: 
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - local

  mongo_satelite: 
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - local

  registro: 
    image: alertas/node
    build: ./src/services/registro
    command: npm start
    ports: 
     - "3000:3000"
    volumes:
     - ./src/services/registro:/usr/app
    depends_on:
      - kafka
      - mongo_humano
      - mongo_satelite
    links:
      - mongo_humano
      - mongo_satelite
    networks:
      - local

  consulta-humano: 
    image: alertas/node
    build: ./src/services/consulta-humano
    command: npm start
    ports: 
     - "3001:3000"
    volumes:
     - ./src/services/consulta-humano:/usr/app
    depends_on:
      - kafka
      - mongo_humano
      - mongo_satelite
    links:
      - mongo_humano
      - mongo_satelite
    networks:
      - local
      
networks:
  local:
    driver: bridge